@domain = http://localhost:3000
@userId = {{createdUser.response.body.$.id}}

### aqui farao os testes de API, se tiverem duvidas basta perguntar
### podem utilizar o modelo abaixo e adaptar para os blogs

@blogsId = {{createdBlog.response.body.$.id}}

###
GET {{domain}}/blogs

###
GET {{domain}}/blog/{{blogsId}}

### atualizar blog
PUT {{domain}}/blog/{{blogsId}}
Content-Type: application/json

{
    "title": "blog 5",
    "description": "teewqewqeqweqweeeeee",
    "content": "blaewqeqwwqhblahblah"
}

###
# @name createdBlog
POST {{domain}}/blog
Content-Type: application/json

{
    "title": "blog 5",
    "description": "testeeeeeeee",
    "content": "blahblahblah"
}

### rota usuarios
GET {{domain}}/users

### rota usuario unico
GET {{domain}}/user/{{userId}}

### rota criar usuario
# @name createdUser
POST {{domain}}/user
Content-Type: application/json

{
    "name": "Vitor",
    "email": "vitor@gmail.com",
    "password": "123456"
}

### rota atualizar usuario
PUT {{domain}}/user/{{userId}}
Content-Type: application/json

{
    "name": "VITORIGOR",
    "email": "vitorigor@gmail.com",
    "password": "123456"
}

### rota deletar usuario
DELETE {{domain}}/user/{{userId}}